### ISSUE TITLE
Reconnect on IB Gateway/TWS auto restart

### ISSUE THREAD

**Issue by jvrodrisan** [atreyuxtrading/atreyu-backtrader-api#4]
As we all known, TWS/IBG restarts everyday, now, on the latest versions the session token lasts for a week so you don't have to enter username/password. What I am struggling to make it work, on the restart, is the live data when the IB Gateway restarts. 

Looking at the code, the msg=-504 is well recognized, however, there is no way to resuscribe to the live data feed. Tried many things but there is no way to take it back. 

Thanks

**Comment by jvrodrisan** [comment]
There is needed to relaunch the thread that manages the connection to IB, once this is done, the feed works again.

**Comment by tbilloud** [comment]
Hi @jvrodrisan,
same problem here... how do you relaunch the thread? kill and re-run your python script?

**Comment by tbilloud** [comment]
This worked for me but with an additional correction: removing the 'if' condition when calling self.conn.connect() in the IBStore reconnect() function definition. I replaced:
```
                if self.conn.connect(self.p.host, self.p.port, self.clientId):
                    if not fromstart or resub:
                        self.startdatas()
                    return True  # connection successful
```
with
```
                self.conn.connect(self.p.host, self.p.port, self.clientId)
                self.apiThread = threading.Thread(target=self.conn.run, daemon=True)
                self.apiThread.start()
                if not fromstart or resub:
                    self.startdatas()
                return True  # connection successful
```
